name: Cypress Test

on: push

jobs:
  verification:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install dependencies
        run: npm ci
  cypress-test:
    name: cypress test
    needs: verification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run cypress run
      - name: Upload Screenshoats reports
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - name: Upload video reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: videos
          path: cypress/videos